// src/client/app/App.tsx
import React, { useState } from 'react';

import './App.less';

const App = () => {
  const [message, setMessage] = useState('it\'s the solid rock for providing a mock.');

  return (
    <div className='app'>
      <b>{message}</b>
      <br/>
      <input type="text" value={message} onChange={(e) => setMessage(e.target.value)} />
    </div>
  );
};

export default App;

// src/client/app/App.vue
<template>
    <div id="app">
        <b>{{ msg }}</b>
        <br/>
        <input type="text" v-model="msg" />
    </div>
</template>

<script>
    export default {
        name: 'app',
        data () {
            return {
                msg: 'it\'s the solid rock for providing a mock.'
            }
        }
    }
</script>

<style lang="css">
    #app {
        color: #56b983;
    }
    input {
        min-width: 300px;
    }
</style>
